/* Generate public Vue exports from each .ce.vue file in src/components/.
 * Called by vite.config.js for dev and build: await generateExports().
 * Example: text-field.ce.vue becomes the named export KimaTextField.
 * To add a component: drop a new .ce.vue file into src/components/ — nothing else to change.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";

/** Write src/index.js from component filenames, preserving real named exports. */
export async function generateExports() {
  const folder = new URL("../src/components/", import.meta.url);
  const components = [];
  for (const file of await readdir(folder)) {
    if (!file.endsWith(".ce.vue")) continue;
    const name = file.slice(0, -".ce.vue".length);
    // Filenames are the public API boundary: invalid or duplicate names cannot ship.
    if (!/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(name)) {
      throw new Error(`Invalid KIMA component filename: ${file}`);
    }
    const exportName = `Kima${name.split("-").map((word) => word[0].toUpperCase() + word.slice(1)).join("")}`;
    if (components.some((component) => component.exportName === exportName)) {
      throw new Error(`Duplicate KIMA component export: ${exportName}`);
    }
    components.push({ exportName, path: `./components/${file}` });
  }
  components.sort((a, b) => a.exportName.localeCompare(b.exportName, "en"));
  const content = [
    "/* Generated by scripts/components.js when Vite loads; do not edit this list.",
    " * Add/remove .ce.vue files in src/components instead. Vue usage:",
    ' * import { KimaButton, componentNames } from "@kernel4632/kima";',
    ' * import "@kernel4632/kima/style.css";',
    " */",
    'import "./styles/_tokens.scss";',
    "",
    ...components.map(({ exportName, path }) => `export { default as ${exportName} } from ${JSON.stringify(path)};`),
    "",
    `export const componentNames = ${JSON.stringify(components.map(({ exportName }) => exportName), null, 2)};`,
    "",
  ].join("\n");
  const entry = new URL("../src/index.js", import.meta.url);
  // Avoid unnecessary source changes and dev reloads when the component set is unchanged.
  if (await readFile(entry, "utf8") !== content) await writeFile(entry, content);
}
