/* Generated by scripts/components.js when Vite loads; do not edit this list.
 * Add/remove .ce.vue files in src/components component folders instead. Vue usage:
 * import { FeyoButton, componentNames } from "@kernel4632/feyo";
 * import "@kernel4632/feyo/style.css";
 */
import "./styles/_tokens.scss";

export { default as FeyoBadge } from "./components/badge/badge.ce.vue";
export { default as FeyoButton } from "./components/button/button.ce.vue";
export { default as FeyoButtonGroup } from "./components/button-group/button-group.ce.vue";
export { default as FeyoCard } from "./components/card/card.ce.vue";
export { default as FeyoCheckbox } from "./components/checkbox/checkbox.ce.vue";
export { default as FeyoDialog } from "./components/dialog/dialog.ce.vue";
export { default as FeyoDivider } from "./components/divider/divider.ce.vue";
export { default as FeyoEmptyState } from "./components/empty-state/empty-state.ce.vue";
export { default as FeyoIconButton } from "./components/icon-button/icon-button.ce.vue";
export { default as FeyoLayout } from "./components/layout/layout.ce.vue";
export { default as FeyoMenu } from "./components/menu/menu.ce.vue";
export { default as FeyoNotification } from "./components/notification/notification.ce.vue";
export { default as FeyoProgress } from "./components/progress/progress.ce.vue";
export { default as FeyoSelect } from "./components/select/select.ce.vue";
export { default as FeyoSlider } from "./components/slider/slider.ce.vue";
export { default as FeyoSwitch } from "./components/switch/switch.ce.vue";
export { default as FeyoTable } from "./components/table/table.ce.vue";
export { default as FeyoTabs } from "./components/tabs/tabs.ce.vue";
export { default as FeyoTextField } from "./components/text-field/text-field.ce.vue";
export { default as FeyoTooltip } from "./components/tooltip/tooltip.ce.vue";

export const componentNames = [
  "FeyoBadge",
  "FeyoButton",
  "FeyoButtonGroup",
  "FeyoCard",
  "FeyoCheckbox",
  "FeyoDialog",
  "FeyoDivider",
  "FeyoEmptyState",
  "FeyoIconButton",
  "FeyoLayout",
  "FeyoMenu",
  "FeyoNotification",
  "FeyoProgress",
  "FeyoSelect",
  "FeyoSlider",
  "FeyoSwitch",
  "FeyoTable",
  "FeyoTabs",
  "FeyoTextField",
  "FeyoTooltip"
];
